---
kind: pipeline
type: kubernetes
name: default

environment:
  GOCACHE: /cache/pkg/cache
  GOMODCACHE: /cache/pkg/mod

steps:
  - name: test
    image: golang:1.24
    pull: always
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - go test -v
      - go build
      - go mod vendor

  - name: docker
    image: harbor.ntppool.org/ntppool/drone-kaniko:main
    pull: always
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    settings:
      repo: ntppool/archiver
      registry: harbor.ntppool.org
      auto_tag: true
      tags: SHA7,${DRONE_SOURCE_BRANCH}
      cache: true
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password

volumes:
  - name: go
    temp: {}
  - name: gopkg
    claim:
      name: go-pkg

---
kind: signature
hmac: 422cc8a2306e3b24ee79a5cfab4613f0ebb35d3aec10d3ed73fd1a2c30963ee9

...
