---
kind: pipeline
type: kubernetes
name: default

environment:
  GOCACHE: /cache/pkg/cache
  GOMODCACHE: /cache/pkg/mod

steps:
  - name: test
    image: golang:1.21
    pull: always
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - go test -v
      - go build
      - go mod vendor

  - name: docker
    image: harbor.ntppool.org/ntppool/drone-kaniko:main
    pull: always
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    settings:
      repo: ntppool/archiver
      registry: harbor.ntppool.org
      auto_tag: true
      tags: SHA7,${DRONE_SOURCE_BRANCH}
      cache: true
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password

volumes:
  - name: go
    temp: {}
  - name: gopkg
    claim:
      name: go-pkg

---
kind: signature
hmac: a6005ad08ace78d7666ac2ed4fdc68f797a0fa45366ef8011016adee3801bc7e

...
