#!/usr/bin/env zsh

set -eu

wait=${wait-600}
vault=/vault/secrets/

while `true`; do
    if [ -d $vault ]; then
        for f in $vault/*.env; do
            source $f
        done
    fi
    /archiver/archiver archive || break
    echo waiting $wait seconds
    sleep $wait
done

echo Failed, exiting
