#!/usr/bin/env zsh

set -eu

wait=${wait-600}
vault=/vault/secrets/database.env

while `true`; do
    if [ -e $vault ]; then
        source $vault
    fi
    /archiver/archiver archive || break
    echo waiting $wait seconds
    sleep $wait
done

echo Failed, exiting
